---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
- name: instance_1
  image: docker.io/pycontribs/debian
  pre_build_image: true
- name: instance_2
  image: docker.io/pycontribs/ubuntu
  pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
